# Generated by Django 5.2.8 on 2025-11-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femmes'), ('unisex', 'Unisexe')], default='unisex', max_length=10),
        ),
    ]

