# Generated by Django 5.2.8 on 2025-11-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reference',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]

