# Generated by Django 5.2.8 on 2026-01-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de paiement'), ('paid', 'PayÃ©e'), ('shipped', 'ExpÃ©diÃ©e'), ('delivered', 'LivrÃ©e'), ('canceled', 'AnnulÃ©e')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_session_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]

