# Generated by Django 5.2.8 on 2026-01-15 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payment_method',
            field=models.CharField(default='card', max_length=20),
        ),
    ]

