# Generated by Django 5.2.8 on 2026-01-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]

