# Generated by Codex on 2026-01-26

from decimal import Decimal, ROUND_HALF_UP

from django.db import migrations


def normalize_orderitem_price(apps, schema_editor):
    OrderItem = apps.get_model("shop", "OrderItem")
    for item in OrderItem.objects.all():
        if item.price is None:
            continue
        item.price = Decimal(str(item.price)).quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
        item.save(update_fields=["price"])


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_order_delivered_at_order_phone_order_shipped_at_and_more"),
    ]

    operations = [
        migrations.RunPython(normalize_orderitem_price, migrations.RunPython.noop),
    ]

