# Generated by Codex on 2026-02-02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0012_normalize_orderitem_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_fee",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name="SiteVisit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("path", models.CharField(max_length=255)),
                ("method", models.CharField(default="GET", max_length=10)),
                ("status_code", models.PositiveSmallIntegerField(default=200)),
                ("referrer", models.CharField(blank=True, max_length=500)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="sitevisit",
            index=models.Index(fields=["created_at"], name="shop_sitevi_created_9f2f09_idx"),
        ),
        migrations.AddIndex(
            model_name="sitevisit",
            index=models.Index(fields=["path"], name="shop_sitevi_path_3e63c4_idx"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "En attente de paiement"),
                    ("paid", "Payée"),
                    ("shipped", "Expédiée"),
                    ("delivered", "Livrée"),
                    ("canceled", "Annulée"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
